/*
 * leds.c
 *
 * Created: 25.04.2014 12:28:50
 *  Author: stenkelfled
 */ 
#include <avr/io.h>
#include <Leds.h>

void usart_init(void){
	USARTC1.BAUDCTRLA = 2; //BSEL = 2 --> 3,333 MHz @f_per = 10MHz; this are 0.3us/spi-bit and 1.2us per data bit
	USARTC1.CTRLA = USART_DREINTLVL_LO_gc;
	USARTC1.CTRLB = USART_TXEN_bm;
	USARTC1.CTRLC = USART_CMODE_MSPI_gc;
	USARTC1.CTRLA = USART_DREINTLVL_MED_gc;
}

void dma_init(void){
	DMA.CTRL = DMA_ENABLE_bm;
	DMA.CTRL |= DMA_DBUFMODE_DISABLED_gc | DMA_PRIMODE_CH0123_gc;
	DMA.CH0.CTRLA = DMA_CH_SINGLE_bm | DMA_CH_BURSTLEN_1BYTE_gc;
	DMA.CH0.ADDRCTRL = DMA_CH_SRCRELOAD_BLOCK_gc | DMA_CH_SRCDIR_INC_gc | DMA_CH_DESTRELOAD_NONE_gc | DMA_CH_DESTDIR_FIXED_gc;
	DMA.CH0.TRIGSRC = DMA_CH_TRIGSRC_USARTC1_DRE_gc;
	DMA.CH0.TRFCNT = LED_COUNT*BYTES_PER_LED;
}